package com.example.data.remote

object DiscordHelper {

    // Discord Permission Bitmask Constants
    const val PERM_ADMINISTRATOR = 8L
    const val PERM_MANAGE_CHANNELS = 16L
    const val PERM_MANAGE_GUILD = 32L
    const val PERM_VIEW_AUDIT_LOG = 128L
    const val PERM_VIEW_CHANNEL = 1024L
    const val PERM_SEND_MESSAGES = 2048L
    const val PERM_MANAGE_MESSAGES = 8192L
    const val PERM_EMBED_LINKS = 16384L
    const val PERM_ATTACH_FILES = 32768L
    const val PERM_READ_MESSAGE_HISTORY = 65536L
    const val PERM_USE_EXTERNAL_EMOJIS = 262144L
    const val PERM_MANAGE_ROLES = 268435456L
    const val PERM_USE_SLASH_COMMANDS = 2147483648L

    /**
     * Recommended permissions for IVE Fanroom Bot:
     * Manage Roles + View Channels + Send Messages + Manage Messages + Embed Links + Read History + Slash Commands
     */
    val DEFAULT_RECOMMENDED_PERMISSIONS = PERM_MANAGE_ROLES or
            PERM_VIEW_CHANNEL or
            PERM_SEND_MESSAGES or
            PERM_MANAGE_MESSAGES or
            PERM_EMBED_LINKS or
            PERM_ATTACH_FILES or
            PERM_READ_MESSAGE_HISTORY or
            PERM_USE_SLASH_COMMANDS

    fun generateInviteUrl(clientId: String, permissions: Long = DEFAULT_RECOMMENDED_PERMISSIONS): String {
        val cleanClientId = clientId.trim().ifEmpty { "YOUR_CLIENT_ID" }
        return "https://discord.com/api/oauth2/authorize?client_id=$cleanClientId&permissions=$permissions&scope=bot%20applications.commands"
    }

    fun validateToken(token: String): Pair<Boolean, String> {
        val trimmed = token.trim()
        if (trimmed.isEmpty()) return Pair(false, "봇 토큰을 입력해주세요.")
        // Discord bot tokens typically have 3 segments separated by dots
        val parts = trimmed.split(".")
        if (parts.size != 3) {
            return Pair(false, "디스코드 봇 토큰 형식(3개 파트 구분)이 올바르지 않습니다.")
        }
        if (trimmed.length < 50) {
            return Pair(false, "토큰 길이가 너무 짧습니다.")
        }
        return Pair(true, "유효한 디스코드 봇 토큰 형식입니다.")
    }

    /**
     * Generates a complete ready-to-run 24/7 discord.py script for external cloud hosting (Railway, Fly.io, Cloud Run)
     */
    fun generatePythonBotScript(
        botName: String,
        prefix: String,
        statusText: String,
        hasGemini: Boolean
    ): String {
        return """
# ==========================================
# $botName - 24/7 Discord Production Bot
# Generated by DIVE Bot Studio (Android)
# ==========================================

import discord
from discord.ext import commands
import os
import aiohttp

intents = discord.Intents.default()
intents.message_content = True
intents.members = True

bot = commands.Bot(command_prefix='$prefix', intents=intents)

STATUS_MESSAGE = "$statusText"
GEMINI_KEY = os.getenv("GEMINI_API_KEY", "")

@bot.event
async def on_ready():
    print(f'✨ {bot.user} 온라인 성공! 24시간 가동 시작.')
    await bot.change_presence(activity=discord.Game(name=STATUS_MESSAGE))

@bot.command(name="핑")
async def ping(ctx):
    latency = round(bot.latency * 1000)
    await ctx.send(f'🏓 퐁! 응답 지연시간: {latency}ms (24시 정상 가동 중)')

@bot.command(name="원영")
async def wonyoung_chat(ctx, *, message: str):
    await ctx.send(f'💖 [원영적 사고] {ctx.author.mention}님, "{message}" 고민이시군요! 완전 럭키비키잖아🍀 오늘도 DIVE 응원해요!')

@bot.command(name="응원법")
async def fanchant(ctx, song: str = "해야"):
    await ctx.send(f'📢 [아이브 - {song}] 공식 응원법: 안유진! 가을! 레이! 장원영! 리즈! 이서! 아.이.브! 💖')

if __name__ == '__main__':
    TOKEN = os.getenv("DISCORD_BOT_TOKEN")
    if TOKEN:
        bot.run(TOKEN)
    else:
        print("❌ DISCORD_BOT_TOKEN 환경변수를 설정해주세요.")
        """.trimIndent()
    }

    /**
     * Generates Dockerfile for 24/7 zero-configuration hosting
     */
    fun generateDockerfile(): String {
        return """
# Production Dockerfile for DIVE Bot
FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir discord.py aiohttp
COPY bot.py .
CMD ["python", "bot.py"]
        """.trimIndent()
    }
}
